version: '3.8'

services:
  # Base de Datos para Estefanía (.NET)
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password

  # TU Base de Datos (Lizeth - PHP) - Aquí está el cambio del puerto
  postgres_db:
    image: postgres:latest
    container_name: postgres_db_container
    ports:
      - "5433:5432"  # <-- CAMBIO: Usamos 5433 para que no choque con tu Windows
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: quality_reports
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Base de Datos para Fernanda (Python/Mongo)
  mongodb:
    image: mongo:7
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Liz Portal PHP
  php-portal:
    build: ./src/php-portal
    container_name: php_portal_container
    ports:
      - "8081:80"
    volumes:
      - ./src/php-portal:/var/www/html
    depends_on:
      - postgres_db

volumes:
  postgres_data:
  mongo_data:
